### ISSUE TITLE
Determine ranking system for puzzles

### ISSUE THREAD

**Issue by j127** [codeselfstudy/codeselfstudy_django#6]
Discussion is in Slack: `#engine-room`.

**Comment by datadaveshin** [comment]
Maybe before it's set, we can figure out the number of problems in leetcode for each level?

**Comment by j127** [comment]
Sounds good. I'll post on Slack.

**Comment by j127** [comment]
I'm closing old issues while seeing if it still funs. I think we did this already.

**Comment by j127** [comment]
BTW, it looks like Github has a discussions feature on this repo:
https://github.com/codeselfstudy/codeselfstudy_django/discussions
